server:
  port: ${SERVER_PORT:9091}
  error:
    include-message: always
    include-binding-errors: always

spring:
  config:
    import: configserver:${CONFIG_SERVER_URI:http://localhost:9999}
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/userdb}
  cloud:
    config:
      fail-fast: true
      retry:
        initial-interval: 1000
        max-attempts: 10
        max-interval: 5000
        multiplier: 1.5
  rabbitmq:
    host: ${RABBITMQ_HOSTNAME:localhost}
    port: ${RABBITMQ_PORT:5672}

app:
  user-verif-url: ${GATEWAY_URI:http://localhost:9090}
